name = "survey-widget"
type = "theme"
uid = "43394cbe-c2e0-f590-6060-6332843f9b75979b3af2"

[[extensions]]
type = "theme"
name = "survey-widget"

[[extensions.files]]
path = "assets/*"

[[extensions.files]]
path = "blocks/*.liquid"
